spring:
  application:
    name: auth-service
  jackson:
    default-property-inclusion: non_null
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        default_schema: auth
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog.yml
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

event:
  bootstrap-servers: ${KAFKA_URL}
  service-name: ${spring.application.name}

jwt:
  issuer: tunepoint
  access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:3600000}
  refresh-token-ttl: ${JWT_REGRESH_TOKEN_TTL:86400000}

confirmation:
  attempts: 3
  code:
    due-period: 1h
    block-resend-period: 1m
    length: 4
  email:
    template: "email_confirm"
    subject: "Tunepoint. Email confirmation"

security:
  secret: ${SECURITY_SECRET:secret}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8765/eureka}
